Updated syntax

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -25,19 +25,19 @@ jobs:
         run: docker push ${{ secrets.DOCKER_USERNAME }}/task-app:latest
       - name: Debug secret presence
         run: |
-        if [ -z "${{ secrets.EC2_HOST }}" ]; then
-          echo "EC2_HOST missing"
-          exit 1
-        else
-          echo "EC2_HOST secret is present"
-        fi
+         if [ -z "${{ secrets.EC2_HOST }}" ]; then
+           echo "EC2_HOST missing"
+           exit 1
+          else
+            echo "EC2_HOST secret is present"
+          fi
 
-        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
-          echo "DOCKER_USERNAME missing"
-          exit 1
-        else
-          echo "DOCKER_USERNAME secret is present"
-        fi
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+            echo "DOCKER_USERNAME missing"
+            exit 1
+          else
+            echo "DOCKER_USERNAME secret is present"
+          fi
 
       - name: Test DNS resolution from runner
         run: |
